### ISSUE TITLE
bennet indicator plot

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/SOE-NEFMC#1]
I altered the plot to show the focal components specifically referenced in the text instead of the aggregate, but left the total revenue line for reference (it now aligns with the plots above). Need to check this with Geret and John to see if it works. 

Legend formatting needs help; previewed position is find but pdf is still too large, and order reversed between plots.

**Comment by slarge** [comment]
Suggestion to improve the legend: turn off the legend for one of the plots and remove benthivores and benthos from the labels since they are described in the figure title. So basically the 2 plots will share a legend. I think it is also possible to create a separate "grob" for the legend and then patchwork everything into a 3 panel plot instead of a 2 panel plot -- or, if you ignore the first suggestion a 4 panel plot.

**Comment by sgaichas** [comment]
We now have one shared legend but a blank one for alignment of the other plot; I will try to implement a better solution with a separate legend grob centered under both plots while this is in policy review

**Comment by sgaichas** [comment]
fixed with https://github.com/NOAA-EDAB/SOE-NEFMC/commit/8a8627feab62b2fcb0ea88b47d1f2edddcb70264
